version: 2

repo:
  public: vue-client-sdk
  private: vue-client-sdk-private

publications:
  - url: https://www.npmjs.com/package/launchdarkly-vue-client-sdk
    description: npm

jobs:
  - docker:
      image: node:16.15.1-buster
    template:
      name: npm

documentation:
  gitHubPages: true
  title: LaunchDarkly Vue SDK

sdk:
  displayName: Vue