repo:
  public: vue-client-sdk
  private: vue-client-sdk-private

publications:
  - url: https://www.npmjs.com/package/launchdarkly-vue-client-sdk
    description: npm

template:
  name: npm

documentation:
  githubPages: true
  title: LaunchDarkly Vue SDK

sdk:
  displayName: "Vue"